package com.nikolastrapp.activitymanager.enums;

public enum Category{
    MANAGEMENT_ACTIVITIES,
    PLANNED_ACTIVITIES,
    ACTIVITIES_NOT_RELATED_TO_RA,
    INTERNATIONAL_REGISTRATION_ACTIVITIES,
    ACTIVITIES_RELATED_TO_RA,
    UNPLANNED_ON_DEMAND_ACTIVITIES

}
